version: '3'
services:
    web:
        build: .
        ports:
            - "5000:8000"
        volumes:
            - .:/go/src/github.com/ignoshi/core
    mongo:
        image: "mongo"
        environment:
            AUTH: 'no'

